### ISSUE TITLE
Error message with pma function

### ISSUE THREAD

**Issue by cvann1986** [audrey-b/BUGSnet#75]
Hello,

I've been using your wonderful BUGSnet package to conduct an NMA but encountered the following error message when attempting to use the pma function:

"Error: $ operator is invalid for atomic vectors".

I first ran the dataset through the data.prep function and followed the example provided in the documentation. A colleague of mine also encountered the same error message.

Could you please advise?

Thank you,
Chris

**Comment by audrey-b** [comment]
Hi Chris,

I corrected the issue a few weeks ago but haven't released the new version yet. If you install BUGSnet using the following link it should fix your issue:

remotes::install_github("audrey-b/BUGSnet", upgrade = TRUE, build_vignettes = TRUE, dependencies = TRUE)

Best,

Audrey

**Comment by cvann1986** [comment]
Great, thank you so much for the quick response!

**Comment by cvann1986** [comment]
Great, thank you so much for the quick response!
